apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: {{ include "sample.fullname" . }}-redis
    app.kubernetes.io/name: {{ include "sample.fullname" . }}-redis
  name: {{ include "sample.fullname" . }}-redis
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "sample.fullname" . }}-redis
      app.kubernetes.io/name: {{ include "sample.fullname" . }}-redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ include "sample.fullname" . }}-redis
        app.kubernetes.io/name: {{ include "sample.fullname" . }}-redis
        version: redis
    spec:
      containers:
        - image: redis
          imagePullPolicy: Always
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
