apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: {{ include "sample.fullname" . }}-redis
    app.kubernetes.io/name: {{ include "sample.fullname" . }}-redis
  name: {{ include "sample.fullname" . }}-redis
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "sample.fullname" . }}-redis
      app.kubernetes.io/name: {{ include "sample.fullname" . }}-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ include "sample.fullname" . }}-redis
        app.kubernetes.io/name: {{ include "sample.fullname" . }}-redis
        version: redis
    spec:
      containers:
        - image: redis
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
              name: redis
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
