apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-redis
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-redis
        version: master
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
