apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-redis
  labels:
    app: {{ include "fullname" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "fullname" . }}-redis
    helm.sh/chart: {{ include "chart" . }}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: {{ include "fullname" . }}-redis
      # app.kubernetes.io/instance: {{ .Release.Name }}
      # app.kubernetes.io/name: {{ include "fullname" . }}-redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "fullname" . }}-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ include "fullname" . }}-redis
        version: stable
    spec:
      containers:
        - image: redis
          imagePullPolicy: Always
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 120Mi
            limits:
              cpu: 110m
              memory: 132Mi
