apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-redis
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}-redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: {{ template "fullname" . }}-redis
