{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-redis
  labels:
    app: {{ template "fullname" . }}-redis
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-redis
    spec:
      containers:
      - name: master
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-redis
  labels:
    app: {{ template "fullname" . }}-redis
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: {{ template "fullname" . }}-redis
{{- end -}}
