{{- if .Values.redis.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-redis
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}-redis
        version: {{ .Values.image.tag }}
    spec:
      containers:
      - name: master
        image: redis
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-redis
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}-redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: {{ template "fullname" . }}-redis
{{- end -}}
