# gitlab-ci

image: docker:stable

stages:
  - package
  - docker_build

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

package:
  image: node:13
  stage: package
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

docker_build:
  image: opspresso/builder:v0.7.69
  services:
    - docker:dind
  stage: docker_build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -f Dockerfile -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
