# gitlab-ci

image: docker:stable

services:
  - docker:dind

stages:
  - build
  - package

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

cache:
  paths:
    - node_modules/

build:
  image: node:13
  stage: build
  script:
    - ./build.sh build
  artifacts:
    paths:
      - node_modules/

docker:
  image: opspresso/builder:v0.7.69
  stage: package
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - ./build.sh docker

helm:
  image: opspresso/builder:v0.7.69
  stage: package
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - ./build.sh helm
