replicaCount: 1
image:
  repository: acme
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
ingress:
  enabled: true
  basedomain: apps.opspresso.com
hpa:
  enabled: true
  min: 1
  max: 30
  cpu: 50
env:
- name: REDIS_URL
  value: "redis://sample-redis.default:6379"
configmap:
  enabled: false
secret:
  enabled: false
