# Default values for acme.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
imagePullSecrets:
image:
  pullPolicy: Always
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
ingress:
  enabled: true
basedomain: apps.nalbam.com
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
