fullnameOverride: sample-node

replicaCount: 1

profile: default

namespace: development

image:
  repository: docker-registry.127.0.0.1.nip.io:30500/sample-node
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000

ingress:
  enabled: true
  subdomain: sample-node
  basedomain: 127.0.0.1.nip.io

autoscaling:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 120m
    memory: 153Mi

readinessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 3
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 3
  periodSeconds: 10
  failureThreshold: 3

env:
  - name: MESSAGE
    value: "hello world"

configmap:
  enabled: false

secret:
  enabled: false
