# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: docker-registory/sample-node
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: node
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi
ingress:
  enabled: true
basedomain: apps.opspresso.com
env:
- name: REDIS_URL
  value: "redis://redis-master:6379"
